name: Matrix Demo
on: push
jobs: 
    build:
        strategy:
            matrix:
                node-version: [ 12, 14, 16]
                operation-system: [ubuntu-latest, windows-lastest]
        runs-on: ${{ matrix.operation-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build project
              run: npm run build
